
// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview AI-driven tool that analyzes images and videos to detect potential deepfakes.
 *
 * - analyzeMedia - A function that analyzes media for deepfakes.
 * - AnalyzeMediaInput - The input type for the analyzeMedia function.
 * - AnalyzeMediaOutput - The return type for the analyzeMedia function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeMediaInputSchema = z.object({
  mediaDataUri: z
    .string()
    .describe(
      "An image or video file, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type AnalyzeMediaInput = z.infer<typeof AnalyzeMediaInputSchema>;

const AnalyzeMediaOutputSchema = z.object({
  riskAssessment: z.object({
    isRisky: z.boolean().describe('Whether the content is a potential deepfake.'),
    riskScore: z.number().describe('A score indicating the likelihood of it being a deepfake (0-100).'),
    reason: z.string().describe('The detailed reason for the deepfake assessment.'),
  }),
  flags: z.array(z.string()).describe('Specific flags raised during the analysis (e.g., facial-inconsistencies, audio-mismatch).'),
});
export type AnalyzeMediaOutput = z.infer<typeof AnalyzeMediaOutputSchema>;

export async function analyzeMedia(input: AnalyzeMediaInput): Promise<AnalyzeMediaOutput> {
  return analyzeMediaFlow(input);
}

const prompt = ai.definePrompt({
  name: 'analyzeMediaPrompt',
  input: {schema: AnalyzeMediaInputSchema},
  output: {schema: AnalyzeMediaOutputSchema},
  prompt: `You are an expert in digital forensics specializing in deepfake detection.
  Analyze the following media file and provide a risk assessment on whether it is a deepfake.

Media: {{media url=mediaDataUri}}

Consider these factors for deepfake indicators:
- Unnatural facial movements or expressions.
- Inconsistencies in lighting, shadows, or reflections.
- Blurring or distortion around the edges of a subject.
- Lack of blinking or unnatural blinking patterns.
- Mismatches between audio and lip movements.
- Artifacts in the video or image background.

Set the isRisky field to true if you suspect a deepfake, assigning a riskScore from 0-100. Provide a detailed reason for your assessment, pointing to specific evidence in the media.
Provide up to 3 specific flags that justify your conclusion (e.g., 'facial-inconsistencies', 'lighting-mismatch', 'audio-sync-issue'). If it appears real, state that clearly.

Output should conform to the AnalyzeMediaOutputSchema schema.
  `,
});

const analyzeMediaFlow = ai.defineFlow(
  {
    name: 'analyzeMediaFlow',
    inputSchema: AnalyzeMediaInputSchema,
    outputSchema: AnalyzeMediaOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
